//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudCode.Authoring.Client.Http;

//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


namespace Unity.Services.CloudCode.Authoring.Client.Models
{
    /// <summary>
    /// Language enum.
    /// </summary>
    /// <value>The language of the script.</value>
    [Preserve]
    [JsonConverter(typeof(StringEnumConverter))]
    internal enum Language
    {
        /// <summary>
        /// Enum JS for value: JS
        /// </summary>
        [EnumMember(Value = "JS")]
        JS = 1,


    }
}



