//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;

namespace Unity.Services.CloudCode.Internal.Http
{
    /// <summary>Enum for how handling missing members when deserializing.</summary>
    enum MissingMemberHandling // IMPORTANT - This class should be internal and not public.
    {
        /// <summary>Throw an error when a member is missing</summary>
        Error,
        /// <summary>Ignore missing members</summary>
        Ignore
    }

    /// <summary>
    /// DeserializationSettings class.
    /// </summary>
    class DeserializationSettings // IMPORTANT - This class should be internal and not public.
    {
        /// <summary>MissingMemberHandling is set to Error by default.</summary>
        public MissingMemberHandling MissingMemberHandling = MissingMemberHandling.Error;
    }
    
}
