//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.CloudCode.Internal.Http;



namespace Unity.Services.CloudCode.Internal.Models
{
    /// <summary>
    /// Scope information for the function execution.
    /// </summary>
    [Preserve]
    [DataContract(Name = "RunModuleArguments_scope")]
    internal class RunModuleArgumentsScope
    {
        /// <summary>
        /// Scope information for the function execution.
        /// </summary>
        /// <param name="type">The type of scope.</param>
        /// <param name="id">The ID of the scope.</param>
        [Preserve]
        public RunModuleArgumentsScope(TypeOptions type = default, string id = default)
        {
            Type = type;
            Id = id;
        }

        /// <summary>
        /// The type of scope.
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeOptions Type{ get; }
        
        /// <summary>
        /// The ID of the scope.
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id{ get; }
    
        /// <summary>
        /// The type of scope.
        /// </summary>
        /// <value>The type of scope.</value>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeOptions
        {
            /// <summary>
            /// Enum MultiplayerSession for value: multiplayerSession
            /// </summary>
            [EnumMember(Value = "multiplayerSession")]
            MultiplayerSession = 1,
            /// <summary>
            /// Enum Player for value: player
            /// </summary>
            [EnumMember(Value = "player")]
            Player = 2
        }

        /// <summary>
        /// Formats a RunModuleArgumentsScope into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "type," + Type + ",";
            if (Id != null)
            {
                serializedModel += "id," + Id;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a RunModuleArgumentsScope as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var typeStringValue = Type.ToString();
            dictionary.Add("type", typeStringValue);
            
            if (Id != null)
            {
                var idStringValue = Id.ToString();
                dictionary.Add("id", idStringValue);
            }
            
            return dictionary;
        }
    }
}
