//-----------------------------------------------------------------------------
// <auto-generated>
//     DO NOT MODIFY.
//
//     The members of this client module class are populated by the Cloud Code
//     Source Generator from the linked Cloud Code module
//     (see the [CloudModuleClient] attribute below). The generated bindings are
//     emitted into a separate partial of this class at compile time.
//
//     Any members you add here may conflict with the generated bindings and
//     will be overwritten when the source is regenerated. Edit the Cloud module
//     instead and let the generator update the client bindings.
// </auto-generated>
//-----------------------------------------------------------------------------

using Unity.Services.CloudCode;

namespace CloudCodeModuleAssemblyTemplate.Client
{
    [CloudModuleClient(typeof(CloudCodeModuleAssemblyTemplate.Cloud.CloudCodeModuleCloudTemplate))]
    public partial class CloudCodeModuleClientTemplate
    {
        // Populated by the Cloud Code Source Generator. Do not modify.
    }
}
